# Swagger
swagger.title=Coea Data API Docs
swagger.description=Coea Data API
swagger.version=v0.1

spring.mvc.pathmatch.matching-strategy=ant-path-matcher

tomcat.ajp.protocol=AJP/1.3
tomcat.ajp.enabled=true

spring.profiles.active=local
